export const monthInEnglish: string[] = ["January", "February",
"March", "April", "May", "June", "July", "August",
"September", "October", "November", "December"]

export const monthsInArabic: string[] = ['يناير', 'فبراير', 'مارس', 'إبريل', 'مايو', 'يونيه', 'يوليه', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر']

export const weekDaysInEnglish: string [] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

export const weekDaysInArabic: string[] = ['السبت', 'الجمعه', 'الخميس', 'الأربعاء', 'الثلاثاء', 'الأثنين', 'الأحد']

export const arabicDigits: string [] = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩']