/*
 * Copyright (C) 2022 Application Library Engineering Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const monthInEnglish: string[] = ["January", "February",
"March", "April", "May", "June", "July", "August",
"September", "October", "November", "December"]

export const monthsInArabic: string[] = ['يناير', 'فبراير', 'مارس', 'إبريل', 'مايو', 'يونيه', 'يوليه', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر']

export const weekDaysInEnglish: string [] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

export const weekDaysInArabic: string[] = ['السبت', 'الجمعه', 'الخميس', 'الأربعاء', 'الثلاثاء', 'الأثنين', 'الأحد']

export const arabicDigits: string [] = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩']